### ISSUE TITLE
BottomNavigationBarItem needs to be updated

### ISSUE THREAD

**Issue by Zazo032** [rodydavis/navigation_rail#10]
`BottomNavigationBarItem`'s `title` property was deprecated after Flutter `1.19.0`:

```
'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
```

However, if using `label`, the plugin throws an error:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building LayoutBuilder:
'package:flutter/src/widgets/text.dart': Failed assertion: line 56 pos 15: 'child != null': is not true.

The relevant error-causing widget was: 
  LayoutBuilder file:///C:/Users/crist/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/navigation_rail-1.5.0/lib/navigation_rail.dart:56:14
When the exception was thrown, this was the stack: 
#2      new DefaultTextStyle (package:flutter/src/widgets/text.dart:56:15)
#3      NavRail._buildTab (package:navigation_rail/navigation_rail.dart:224:17)
#4      NavRail.build.<anonymous closure> (package:navigation_rail/navigation_rail.dart:136:27)
#5      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:124:33)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2626:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by rodion-m** [comment]
Fix: https://github.com/rodydavis/navigation_rail/pull/11

**Comment by rodydavis** [comment]
Awesome!
